# 1. We don't need to use `sudo`, and can instead use containers for faster builds
sudo: false
# 2. This is a node.js JS project
language: node_js
# 3. These are the various versions of node.js we want to test against
node_js:
  - "8"
# 4. We'd like to cache our node_modules dir, because it won't change very often
cache:
  directories:
    - "node_modules"
# 5. Notify by email when build fails
notifications:
  email:
    recipients:
      - mpouxlhs.xar@gmail.com
    on_success: never # default: change
    on_failure: always # default: always